<?php echo $this->doctype() ?>
<html lang="ru">
    <head>
        <title><?php echo $_SERVER['HTTP_HOST'] ?></title> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <link rel="shortcut icon" href="images/favicon.ico">
        <?php echo $this->headScript() ?>
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
        <!--[if lt IE 9]>
          <script src="/domains/default/js/html5shiv.js"></script>
        <![endif]-->
    </head>
    <body class="blue">
        <?php echo $this->layout()->content ?>
        <div class="container">
            <header>
                   <div class="row">
                         <div class="logo">
                                 <h1 class="text-center animated fadeInDown delayTwo"><?php echo $_SERVER['HTTP_HOST'] ?></h1>
                         </div>
                    </div>				
            </header>

                 <div class="row">
                         <div class="col-md"><h2 class="text-center tagline">Сайт находится в разработке</h2></div>
                 </div>

                 <div class="row">
                         <ul id="countdown" ms-user-select="none" class="animated fadeInUp delay">

                                 <li>
                                 <span id="days-sub">дней</span>
                                 <input class="knob" id="days" data-readonly=true data-min="0" data-max="366" data-skin="tron" data-width="150" data-height="150" data-thickness="0.1" data-fgcolor="#ecf0f1">
                                 </li>

                                 <li>
                                 <span id="hours-sub">часов</span>
                                 <input class="knob" id="hours" data-readonly=true data-min="0" data-max="24" data-skin="tron" data-width="150" data-height="150" data-thickness="0.1" data-fgcolor="#ecf0f1">
                                 </li>

                                 <li>
                                 <span id="mins-sub">минут</span>
                                 <input class="knob" id="mins" data-readonly=true data-min="0" data-max="60" data-skin="tron" data-width="150" data-height="150" data-thickness="0.1" data-fgcolor="#ecf0f1">
                                 </li>

                                 <li>	
                                 <span id="secs-sub">секунд</span>			
                                 <input class="knob" id="secs" data-readonly=true data-min="0" data-max="60" data-skin="tron" data-width="150" data-height="150" data-thickness="0.1" data-fgcolor="#ecf0f1">
                         </li>

                         </ul>	
                 </div>

                 <div class="row text-center">
                 <div class="col-md">

                         <h3>Подпишитесь, чтобы узнать, когда мы откроемся</h3>

                         <!-- Update here: Begin MailChimp Signup Form -->
                         <form action="http://respooonsive.us7.list-manage1.com/subscribe/post?u=1753278e08f9784d3ee119021&amp;id=d8706eeb51" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="form-inline validate" target="_blank" novalidate>
                         <div class="form-group">
                                 <input type="email" value="" name="EMAIL" class="form-control email email-txt" id="mce-EMAIL" placeholder="Enter your email here" required>
                         </div>
                                 <button type="submit" name="subscribe" id="mc-embedded-subscribe" class="subscribe-btn">Подписаться</button>



                         </form>
                         <!--End of MailChimp Signup Form -->

                 </div>	
                 </div>

                 <div class="row text-center">
                         <div class="icon-effect">
                          <a href="#" class="animated bounceIn delay social-icon icon-twitter"></a>	
                          <a href="#" class="animated bounceIn delay social-icon icon-facebook"></a>
                          <a href="#" class="animated bounceIn delay social-icon icon-google-plus-sign"></a>		
                          <a href="#" class="animated bounceIn delay social-icon icon-flickr"></a>		
                          <a href="#" class="animated bounceIn delay social-icon icon-linkedin-sign"></a>						
                          <a href="#" class="animated bounceIn delay social-icon icon-rss"></a>
                          <a href="#" class="animated bounceIn delay social-icon icon-youtube-sign"></a>
                          <a href="#" class="animated bounceIn delay social-icon icon-pinterest"></a>
                         </div>	
                 </div>

         </div>

                 <footer>
                         <div class="text-center"><p>Copyright &copy; 2013 <?php echo $_SERVER['HTTP_HOST'] ?></p></div>
                 </footer>		

         <script type="text/javascript">
         ( function ( $ ) {
                 "use strict";
                         $(document).ready(function(){

                                 $("#countdown").countdown({
                                         date: "10 august 2014 12:00:00", //follow this date format
                                         format: "on"
                                 },

                                 function() {
                                         // callback function
                                 });
                         });
                         } ( jQuery ) );
         </script>
    </body>
</html>