<div class="m-b-md">
    <h3 class="m-b-none">Элементы инфоблока</h3>
</div>

<section class="panel panel-default">
    <div class="row text-sm wrapper">
        <div class="col-sm-5 m-b-xs">
            <a href="<?php echo $this->url(array('iElementId' => 0, 'iCategoryId' => intval($this->oCategory->id_category),), 'iblock-editelement')?>" class="btn btn-sm btn-success"><i class="fa fa-plus-circle"></i> Новый элемент</a>        
        </div>
        <div class="col-sm-4 m-b-xs"></div>
        <div class="col-sm-3">
            <div class="input-group">
                <input type="text" class="input-sm form-control" placeholder="Поиск">
                <span class="input-group-btn">
                    <button class="btn btn-sm btn-default" type="button">Искать</button>
                </span>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped b-t b-light text-sm">
            <thead>
                <tr>
                    <th width="20"><input type="checkbox"></th>
                    <th>ID</th>
                    <th class="th-sortable" data-toggle="class">Название</th>
                    <th>URL</th>
                    <th>Статус</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->oElements->count() > 0) { ?>
                <?php foreach ($this->oElements->getCurrentItems() as $oElement) { ?>
                <tr>
                    <td><input type="checkbox" name="iblock_element_selected[]" value="2"></td>
                    <td><?php echo $oElement->id_element;?></td>
                    <td><?php echo $oElement->name?></td>
                    <td><?php echo $oElement->url;?></td>
                    <td><?php //echo $this->aStatuses[$oElement->id_status]->name?></td>
                    <td>
                        <a href="<?php echo $this->url(array('iElementId' => $oElement->id_element, 'iCategoryId' => $oElement->id_category,), 'iblock-editelement')?>" title="Редактировать"><i class="fa fa-x2 fa-pencil"></i></a> 
                        <a href="/" title="Удалить"><i class="fa fa-x2 fa-trash-o"></i></a>
                    </td>
                </tr>
                <?php } ?>
                <?php } else { ?>
                <tr>
                    <td colspan="6">
                        <div class="alert alert-info">
                            <i class="fa fa-info-circle"></i> <b>В данной категории нет страниц</b>
                        </div>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <footer class="panel-footer">
        <div class="row">
            <div class="col-sm-4 hidden-xs"></div>
            <div class="col-sm-4 text-center"></div>
            <div class="col-sm-4 text-right text-center-xs">
                <?php echo $this->paginationControl($this->oElements, 'Sliding', 'partials/pagination.phtml');?>
            </div>
        </div>
    </footer>
</section>