<input type="hidden" id="advancedimageSettings" data-element-id="<?=$this->oElement->id_element?>" data-url="<?=$this->url(array('iElementId' => $this->oElement->id_element, 'iIblockId' => $this->oCategory->id_iblock),'iblock-ajax-element-images')?>" />
<div class="m-b-md">
    <h3 class="m-b-none"><?php echo (strlen($this->oElement->name) > 0)? $this->oElement->name : 'Новый элемент' ?></h3> 
</div>
<form role="form"  enctype="multipart/form-data" id="ibelement-edit-form" class="form-horizontal" method="POST" action="<?php echo $this->url();?>">
    <section class="panel panel-default">
        <header class="panel-heading bg-light">
            <ul class="nav nav-tabs nav-justified">
                <li class="active"><a href="#tab-ibelement" data-toggle="tab">Элемент</a></li>
                <li><a href="#tab-images" data-toggle="tab">Изображения</a></li>
                <li><a href="#tab-seo" data-toggle="tab">SEO</a></li>
            </ul>
        </header>
        <div class="panel-body">
            <div class="tab-content">
                <div class="tab-pane active" id="tab-ibelement">
                    <div class="form-group">
                        <label for="ibelementIdCategory" class="col-lg-1 control-label">Категория</label>
                        <div class="col-lg-11">
                            <select class="form-control" name="ibelementIdCategory" id="ibelementIdCategory">
                                <option value="0">&mdash;</option>
                                <?php foreach ($this->aCategories as $aCategory) { ?>
                                <option value="<?php echo $aCategory['id_category'];?>" <?php echo ($aCategory['id_category'] == $this->oElement->id_category)?'selected="selected"':'';?>><?php echo str_repeat('&mdash;', $aCategory['level']);?> <?php echo $aCategory['name'];?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ibelementName" class="col-lg-1 control-label">Название</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control" name="ibelementName" id="ibelementName" placeholder="Название элемента" value="<?php echo $this->oElement->name;?>" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ibelementUrl" class="col-lg-1 control-label">URL</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control" name="ibelementUrl" id="ibelementUrl" placeholder="Относительная ссылка" value="<?php echo $this->oElement->url;?>" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ibelementDatePublish" class="col-lg-1 control-label">Дата публикации</label>
                        <div class="col-lg-1">
                            <input type="text" class="form-control datepicker-input" data-date-format="dd.mm.yyyy" name="ibelementDatePublish" id="ibelementDatePublish" value="<?php echo Mg_Common_Helper_Date::toView(( $this->oElement->date_publish != '' ? $this->oElement->date_publish : date('Y-m-d')));?>" />
                        </div>
                        <div class="col-lg-5">
                            <label for="dateSpinnerHH" class="col-lg-1 control-label">ЧЧ</label>
                            <div data-max="23" data-min="0" class="spinner input-group col-lg-2" id="dateSpinnerHH">
                                <input type="text" maxlength="2" name="ibelementDatePublishHH" value="<?=Mg_Common_Helper_Date::getHour($this->oElement->date_publish)?>" class="form-control spinner-input">
                                <div class="btn-group btn-group-vertical input-group-btn">
                                    <button class="btn btn-default spinner-up" type="button">
                                        <i class="fa fa-chevron-up text-muted"></i>
                                    </button>
                                    <button class="btn btn-default spinner-down" type="button">
                                        <i class="fa fa-chevron-down text-muted"></i>
                                    </button>
                                </div>
                            </div>
                            <label for="dateSpinnerMM" class="col-lg-1 control-label">ММ</label>
                            <div data-max="59" data-min="0" class="spinner input-group col-lg-2" id="dateSpinnerMM">
                                <input type="text" maxlength="2" name="ibelementDatePublishMM" value="<?=Mg_Common_Helper_Date::getMinute($this->oElement->date_publish)?>" class="form-control spinner-input">
                                <div class="btn-group btn-group-vertical input-group-btn">
                                    <button class="btn btn-default spinner-up" type="button">
                                        <i class="fa fa-chevron-up text-muted"></i>
                                    </button>
                                    <button class="btn btn-default spinner-down" type="button">
                                        <i class="fa fa-chevron-down text-muted"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ibelementShortDescription" class="col-lg-1 control-label">Короткое описание</label>
                        <div class="col-lg-11">
                            <!--<input type="hidden" name="ibelementShortDescription" id="ibelementShortDescription" value="" />-->
                            <?php //echo $this->partial('partials/wysiwyg.phtml', array('id' => 'ibelementShortDescription', 'text' => $this->oElement->short_text,)) ?>
                            <textarea class="wysiwyg-redactor" name="ibelementShortDescription" id="ibelementShortDescription" style="width: auto; min-height: 600px;">
                                <?=$this->oElement->short_text?>
                            </textarea>
                        </div> 
                    </div>
                    <div class="form-group">
                        <label for="ibelementText" class="col-lg-1 control-label">Подробное описание</label>
                        <div class="col-lg-11"> 
                            <!--<input type="hidden" name="ibelementText" id="ibelementText" value="" />-->
                            <?php //echo $this->partial('partials/wysiwyg.phtml', array('id' => 'ibelementText', 'text' => $this->oElement->text,)) ?>
                            <textarea class="wysiwyg-redactor" name="ibelementText" id="ibelementText" style="width: auto; min-height: 600px;">
                                <?=$this->oElement->text?>
                            </textarea>
                        </div> 
                    </div>
                </div>
                <div class="tab-pane" id="tab-images">
                    <?php if ($this->oElement->id_element > 0) { ?>
                    <div class="form-group">
                        <label class="col-lg-1 control-label">Загрузить файл</label>
                        <div class="col-lg-3">
                            <input type="file" class="filestyle" name="itemImage[]" data-icon="true" data-classIcon="fa fa-folder-o" data-classButton="btn btn-default" data-classInput="form-control inline input-s" data-buttonText="Выберите файл" />
                        </div>
                        <div class="col-lg-3">
                            <input type="file" class="filestyle" name="itemImage[]" data-icon="true" data-classIcon="fa fa-folder-o" data-classButton="btn btn-default" data-classInput="form-control inline input-s" data-buttonText="Выберите файл" />
                        </div>
                        <div class="col-lg-5">
                            <input type="file" class="filestyle" name="itemImage[]" data-icon="true" data-classIcon="fa fa-folder-o" data-classButton="btn btn-default" data-classInput="form-control inline input-s" data-buttonText="Выберите файл" />
                        </div>
                    </div>
                    <div class="line line-dashed line-lg pull-in"></div>
                    <?php if ( !empty($this->aImagePreferences) ) { ?>
                    <input type="hidden" class="_image_preference" id="imagePreference_origin" data-key="origin" data-name="Оригинал" data-size="" />
                    <?php foreach ($this->aImagePreferences as $sImageKey => $aImagePreferences) { ?>
                    <input type="hidden" class="_image_preference" id="imagePreference_<?=$sImageKey?>" data-key="<?=$sImageKey?>" data-name="<?=(!empty($aImagePreferences['name'])?$aImagePreferences['name']:$sImageKey)?>" data-size="<?=$aImagePreferences['width']?>x<?=$aImagePreferences['height']?>" />
                    <?php } ?>
                    <?php } ?>
                    <ul class="list-group gutter list-group-lg list-group-sp sortable">
                    <?php foreach ($this->aImages as $aImage) { ?>
                        <li class="list-group-item" draggable="true" style="display: block;">
                            <span class="pull-right">
                                <a href="#"><i class="fa fa-times icon-muted fa-fw"></i></a>                  
                            </span>
                            <span class="pull-left media-xs"><i class="fa fa-sort text-muted fa m-r-sm"></i> <?=$aImage['order']+1?></span>
                            <div class="clear">
                                <input type="hidden" name="itemImages[]" value="<?=$aImage['origin']['name']?>" />
                                <a href="/pub_img/<?=$aImage['origin']['url']?>" target="_blank"><img src="/pub_img/<?=$aImage['url']?>" /></a>
                            </div>
                        </li>
                    <?php } ?>
                    </ul>
                    <?php } else { ?>
                    <div class="alert alert-info">
                        <i class="fa fa-info-circle"></i> Сохраните элемент, чтобы загрузить изображения
                    </div>
                    <?php } ?>
                </div>
                <div class="tab-pane" id="tab-seo">
                    <div class="form-group">
                        <label for="ibelementTitle" class="col-lg-1 control-label">Title</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control" name="ibelementTitle" id="ibelementTitle" placeholder="Title" value="<?php echo $this->oElement->title;?>" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ibelementKeywords" class="col-lg-1 control-label">Keywords</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control" name="ibelementKeywords" id="ibelementKeywords" placeholder="Keywords" value="<?php echo $this->oElement->keywords;?>" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ibelementDescription" class="col-lg-1 control-label">Description</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control" name="ibelementDescription" id="ibelementDescription" placeholder="Description" value="<?php echo $this->oElement->description;?>" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-offset-1 col-lg-11">
                    <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Сохранить</button> 
                    <button type="submit" name="return" value="1" class="btn btn-success"><i class="fa fa-reply"></i> Сохранить и вернуться</button>
                </div>
            </div>
        </div>
    </section>
</form>

<script type="text/javascript" src="/domains/admin/external/file-input/bootstrap-filestyle.min.js"></script>