<footer>
    <div class="container">    
        <div class="row  footer">
            <div class="col-md-12">          
                <div class="row">
                    <div class="col-md-4">
                        <a href="/"><h4 class="logo-footer">(495)969-81-14</h4></a>
                        <p>
                        Наш специализированный техцентр занимается обслуживанием, диагностикой и ремонтом Toyota и Lexus в Москве. <br/>
                        Техцентр располагает всем необходимым оборудованием, не уступающим дилерскому и собственным складом запчастей. <br/>
                        За 12 лет работы мы отремонтировали тысячи автомобилей и знаем все тонкости ремонта и диагностики Toyota и Lexus.
                        </p>
                    </div> 
                    <div class="col-md-4">
                        <h4>Адрес</h4>
                        <ul class="list-footer">
                            <li><span class="box-small"><i class="icon-time"></i></span>пн-вс 10:00 - 20:00</li>
                            <li><span class="box-small"><i class="icon-building"></i></span>3-й Угрешский проезд, д. 6</li>
                            <li>Москва</li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h4>Контакты</h4>
                        <ul class="list-footer">
                            <li><span class="box-small"><i class="icon-phone"></i></span> <a href="callto:74959698114">(495) 969 81 14</a></li>
                        </ul>
                        <ul class="list-footer">
                            <li><span class="box-small"><i class="icon-desktop"></i></span> <a href="http://camry-service.ru">camry-service.ru</a></li>
                            <li><a href="mailto:info@camry-service.ru">info@camry-service.ru</a></li>
                        </ul>            
                    </div>    
                </div>      
            </div>
        </div>

        <div class="row after-footer">
            <div class="col-md-4"><p><strong>&copy;2010 CAMRY-SERVICE.RU</strong></p></div>
            <div class="col-md-4"><p>Powered by Mechagear CMS</p></div>
            <div class="col-md-4">
                <p><!--
                    <a href="#" class="social-icon-main"><i class="icon-facebook" title="facebook"></i></a>
                    <span class="divider-social"></span>
                    <a href="#" class="social-icon-main"><i class="icon-twitter" title="twitter"></i></a>
                    <span class="divider-social"></span>
                    <a href="#" class="social-icon-main"><i class="icon-google-plus" title="google plus"></i></a>
                    <span class="divider-social"></span>
                    <a href="#" class="social-icon-main"><i class="icon-youtube" title="youtube"></i></a>  -->                     
                </p>
            </div>
        </div>      
    </div> 
</footer>
<!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter23855185 = new Ya.Metrika({id:23855185, webvisor:true, clickmap:true, trackLinks:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/23855185" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->