<header id="home">
    <nav class="navbar navbar-fixed-top" role="navigation">
        <div class="navbar-inner">
            <div class="container">
                <a href="callto:74959698114" class=""><img src="/domains/camry-service.ru/img/logoc.png " alt="logo" class="logo"></a>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/" title="">Главная /</a></li>
                    <li><a href="/action" title="">Акции /</a></li>   
                    <li><a href="/services" title="">Услуги /</a></li>
                    <li><a href="/contact" title="">Адрес /</a></li> 
                </ul>          					
            </div>
        </div>
    </nav>
</header>