<div class="m-b-md">
    <h3 class="m-b-none">Характеристики товаров &laquo;<?php echo $this->oShop->name ?>&raquo;</h3>
</div>
<section class="panel panel-default">
    <header class="panel-heading">
      Характеристики
    </header>
    <div class="row text-sm wrapper">
        <div class="col-sm-5 m-b-xs">
            <a href="<?php echo $this->url(array('iShopId' => $this->oShop->id_shop, 'iPropertyId' => 0), 'shop-categories-properties-edit');?>" class="btn btn-sm btn-success" title="Создать"><i class="fa fa-plus-circle"></i> Добавить характеристику</a>        
        </div>
        <div class="col-sm-4 m-b-xs"></div>
        <div class="col-sm-3">
            <div class="input-group">
                <input type="text" class="input-sm form-control" placeholder="Поиск">
                <span class="input-group-btn">
                    <button class="btn btn-sm btn-default" type="button">Искать</button>
                </span>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped b-t b-light text-sm">
            <thead>
                <tr>
                    <th width="20"><input type="checkbox"></th>
                    <th>ID</th>
                    <th class="th-sortable" data-toggle="class">Название
                        <span class="th-sort">
                            <i class="fa fa-sort-down text"></i>
                            <i class="fa fa-sort-up text-active"></i>
                            <i class="fa fa-sort"></i>
                        </span>
                    </th>
                    <th>Тип</th>
                    <th>Вид</th>
                    <th>Ед. изм.</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->oShopProperties->count() > 0) { ?>
                <?php foreach ($this->oShopProperties->getCurrentItems() as $oProperty) { ?>
                <?
                $oMeasure = Mg_Shop_Helper_Measure::getMeasure($oProperty->id_measure);
                ?>
                <tr>
                    <td>
                        <input type="checkbox" name="property_selected[]" value="2">
                    </td>
                    <td><?php echo $oProperty->id_property;?></td>
                    <td><b><?php echo $oProperty->name?></b></td>
                    <td><?php echo $this->aShopPropertyTypes[$oProperty->type]?></td>
                    <td><?php echo $this->aShopPropertyViewTypes[$oProperty->view_type];?></td>
                    <td><?php echo $oMeasure->name_short?></td>
                    <td>
                        <a href="<?php echo $this->url(array('iShopId' => $this->oShop->id_shop, 'iPropertyId' => $oProperty->id_property), 'shop-categories-properties-edit');?>" title="Редактировать"><i class="fa fa-edit"></i></a> 
                        <a href="#" title="Удалить"><i class="fa fa-trash-o"></i> </a>
                    </td>
                </tr>
                <?php } ?>
                <?php } else { ?>
                <tr>
                    <td colspan="7">
                        <div class="alert alert-info">
                            <i class="fa fa-info-circle"></i> <b>Нет ни одной характеристики</b>
                        </div>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <footer class="panel-footer">
        <div class="row">
            <div class="col-sm-4 hidden-xs"></div>
            <div class="col-sm-4 text-center"></div>
            <div class="col-sm-4 text-right text-center-xs">
                <?php echo $this->paginationControl($this->oShopProperties, 'Sliding', 'partials/pagination.phtml');?>
            </div>
        </div>
    </footer>
</section>