<script type="text/javascript" src="/js/validate.js"></script>
<script>
$(document).ready(function(){
    
});    
</script>
<div class="m-b-md">
    <h3 class="m-b-none"><?php echo (strlen($this->oShopProperty->name) > 0)? $this->oShopProperty->name : 'Новая характеристика' ?></h3> 
</div>
<form role="form" id="property-edit-form" class="form-horizontal" method="POST" action="<?php echo $this->url();?>">
    <section class="panel panel-default">
        <div class="panel-body">
                <div class="form-group">
                    <label for="propertyName" class="col-lg-1 control-label">Название</label>
                    <div class="col-lg-11">
                        <input type="text" class="form-control" name="propertyName" id="propertyName" placeholder="Название характеристики" value="<?php echo $this->oShopProperty->name;?>" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="propertyType" class="col-lg-1 control-label">Тип</label>
                    <div class="col-lg-11">
                        <select class="form-control" name="propertyType" id="propertyType">
                            <?php foreach ($this->aShopPropertyTypes as $sTypeKey => $sTypeName) { ?>
                            <option value="<?=$sTypeKey?>" <?php echo ($sTypeKey != $this->oShopProperty->type) ? '' : 'selected="selected"';?>><?php echo $sTypeName;?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="propertyViewType" class="col-lg-1 control-label">Вид</label>
                    <div class="col-lg-11">
                        <select class="form-control" name="propertyViewType" id="propertyViewType">
                            <?php foreach ($this->aShopPropertyViewTypes as $sTypeKey => $sTypeName) { ?>
                            <option value="<?=$sTypeKey?>" <?php echo ($sTypeKey != $this->oShopProperty->view_type) ? '' : 'selected="selected"';?>><?php echo $sTypeName;?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="propertyMeasure" class="col-lg-1 control-label">Ед. изм.</label>
                    <div class="col-lg-11">
                        <select class="form-control" name="propertyMeasure" id="propertyMeasure">
                            <option value="0">нет</option>
                            <?php if ( $this->oMeasures->count() > 0 ) { ?>
                            <?php foreach ($this->oMeasures->getCurrentItems() as $oMeasure) { ?>
                            <option value="<?=$oMeasure->id_measure?>" <?php echo ($oMeasure->id_measure != $this->oShopProperty->id_measure) ? '' : 'selected="selected"';?>><?php echo $oMeasure->name_full;?> (<?php echo $oMeasure->name_short;?>)</option>
                            <?php } ?>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            
                <div class="form-group">
                    <div class="col-lg-12">
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </div>
                </div>
        </div>
    </section>
</form>