<header class="bg-dark dk header navbar navbar-fixed-top-xs">
    <div class="navbar-header aside-md">
      <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen,open" data-target="#nav,html">
        <i class="fa fa-bars"></i>
      </a>
      <a href="#" class="navbar-brand" data-toggle="fullscreen"><img src="/img/mechagear.png" class="m-r-sm"></a>
      <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".nav-user">
        <i class="fa fa-cog"></i>
      </a>
    </div>
    <?=$this->action('userinfo','userinfo','admin')?>         
</header>