<!-- .aside -->
<aside class="bg-dark lter aside-md hidden-print" id="nav">
<section class="vbox">
    <!---
    <header class="header bg-primary lter text-center clearfix">
        <div class="btn-group">
            <button type="button" class="btn btn-sm btn-dark btn-icon" title="New project"><i class="fa fa-plus"></i></button>
            <div class="btn-group hidden-nav-xs">
                <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown">
                    Выбрать сайт
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu text-left">
                    <li><a href="#">default</a></li>
                    <li><a href="#">servicearea.ru</a></li>
                    <li><a href="#">multitronics.ru</a></li>
                </ul>
            </div>
        </div>
    </header>
    -->
    <section class="w-f scrollable">
        <div class="slim-scroll" data-height="auto" data-disable-fade-out="true" data-distance="0" data-size="5px" data-color="#333333">
        <!-- nav -->
            <nav class="nav-primary hidden-xs">
                <ul class="nav">
                    <li class="active">
                        <a href="/" class="active">
                            <i class="fa fa-rocket icon">
                            <b class="bg-danger"></b>
                            </i>
                            <span>ЦУП</span>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array(),'pages-list')?>"  >
                            <i class="fa fa-file-o icon"><b class="bg-primary dker"></b></i>
                            <span>Страницы</span>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array(),'iblock-list')?>"  >
                            <i class="fa fa-folder-o icon"><b class="bg-primary dker"></b></i>
                            <span>Инфоблоки</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-shopping-cart icon"><b class="bg-warning"></b></i>
                            <span class="pull-right">
                                <i class="fa fa-angle-down text"></i>
                                <i class="fa fa-angle-up text-active"></i>
                            </span>
                            <span>Магазины</span>
                        </a>
                        <ul class="nav lt">
                            <li>
                                <a href="<?php echo $this->url(array(),'shop-list')?>" ><i class="fa fa-angle-right"></i><span>Магазины</span></a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"  >
                            <i class="fa fa-road icon"><b class="bg-primary dker"></b></i>
                            <span>Площадки</span>
                        </a>
                    </li>
                    <li>
                        <a href="#"  >
                            <i class="fa fa-users icon"><b class="bg-primary dker"></b></i>
                            <span>Клиенты</span>
                        </a>
                    </li>
                    <li>
                        <a href="#"  >
                            <i class="fa fa-rub icon"><b class="bg-primary dker"></b></i>
                            <span>Деньги</span>
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url(array(),'users-list')?>">
                            <i class="fa fa-users icon"><b class="bg-primary dker"></b></i>
                            <span>Пользователи</span>
                        </a>
                    </li>
                    <li>
                        <a href="#"  >
                            <i class="fa fa-cogs icon"><b class="bg-primary dker"></b></i>
                            <span>Настройки</span>
                        </a>
                    </li>
                    <li>
                        <a href="#"  >
                            <i class="fa fa-shield icon"><b class="bg-primary dker"></b></i>
                            <span>Защита</span>
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url(array(),'dev-default')?>">
                            <i class="fa fa-code icon"><b class="bg-primary dker"></b></i>
                            <span>Dev</span>
                        </a>
                    </li>
                </ul>
            </nav>
        <!-- / nav -->
        </div>
    </section>

    <footer class="footer lt hidden-xs b-t b-dark">
        <a href="#nav" data-toggle="class:nav-xs" class="pull-right btn btn-sm btn-dark btn-icon">
            <i class="fa fa-angle-left text"></i>
            <i class="fa fa-angle-right text-active"></i>
        </a>
    </footer>
</section>
</aside>
<!-- /.aside -->