<?php if ($this->pageCount > 1): ?>
<ul class="pagination pagination-sm m-t-none m-b-none">
    <!-- Ссылка на предыдущую страницу -->
    <?php if (isset($this->previous)): ?>
    <li><a href="<?php echo $this->url(array('iPage' => $this->previous)); ?>"><i class="fa fa-chevron-left"></i></a></li>
    <?php else: ?>
    <li class="disabled"><span><i class="fa fa-chevron-left"></i></span></li>
    <?php endif; ?>
    
    <!-- Нумерованные ссылки на страницы -->
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
        <li><a href="<?php echo $this->url(array('iPage' => $page)); ?>"><?php echo $page; ?></a></li>
        <?php else: ?>
        <li class="active"><span><?php echo $page; ?></span></li>
        <?php endif; ?>
    <?php endforeach; ?>
    
    <!-- Ссылка на следующую страницу -->
    <?php if (isset($this->next)): ?>
    <li><a href="<?php echo $this->url(array('iPage' => $this->next)); ?>"><i class="fa fa-chevron-right"></i></a></li>
    <?php else: ?>
    <li class="disabled"><span><i class="fa fa-chevron-right"></i></span></li>
    <?php endif; ?>    
</ul>  
<?php endif; ?>