<script>
    $(document).ready(function(){
        $('#page-edit-form').submit(function(){
            $('#pageShortDescription').val($('#wysiwyg-pageShortDescription').cleanHtml());
            $('#pageText').val($('#wysiwyg-pageText').cleanHtml()); 
        });
    });
</script>
<div class="m-b-md">
    <h3 class="m-b-none"><?php echo (strlen($this->oPage->name) > 0)? $this->oPage->name : 'Новая страница' ?></h3> 
</div>
<form role="form" id="page-edit-form" class="form-horizontal" method="POST" action="<?php echo $this->url();?>">
    <section class="panel panel-default">
        <header class="panel-heading bg-light">
            <ul class="nav nav-tabs nav-justified">
                <li class="active"><a href="#tab-page" data-toggle="tab">Страница</a></li>
                <li><a href="#tab-seo" data-toggle="tab">SEO</a></li>
            </ul>
        </header>
        <div class="panel-body">
            <div class="tab-content">
                <div class="tab-pane active" id="tab-page">
                    
                    <div class="form-group">
                        <label for="pageDomainKey" class="col-lg-1 control-label">Проект</label>
                        <div class="col-lg-11">
                            <select class="form-control _validate" name="pageDomainKey" id="pageDomainKey" data-validate-model="Mg_Base_Model_Page" data-validate-name="domain_key" data-id_page="<?=$this->oPage->id_page?>" data-validate-on-success="pageUrl">
                                <option value="">Все</option>
                                <?php foreach ($this->aDomainKeys as $aDomainKey => $aDomainName) { ?>
                                <option value="<?=$aDomainKey?>" <?php echo ($aDomainKey == $this->oPage->domain_key)?'selected="selected"':'';?>><?=$aDomainName?></option>
                                <?php } ?>
                            </select>
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'domain_key'))?>
                        </div>
                    </div>
                    
                    <div class="form-group <?php echo (!empty($this->aErrors['name'])) ? 'has-error' : '' ?>">
                        <label for="pageName" class="col-lg-1 control-label">Название</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control validateable" name="pageName" id="pageName" data-cname="page" data-field="name" data-params="" placeholder="Название страницы" value="<?php echo $this->oPage->name;?>" />
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'name'))?>
                        </div>
                    </div>
                    <div class="form-group <?php echo (!empty($this->aErrors['url'])) ? 'has-error' : '' ?>">
                        <label for="pageUrl" class="col-lg-1 control-label">URL</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control _validate" data-validate-model="Mg_Base_Model_Page" data-validate-name="url" data-id_page="<?=$this->oPage->id_page?>" data-dynamic-parameters="domain_key:pageDomainKey;" name="pageUrl" id="pageUrl" placeholder="Относительная ссылка" value="<?php echo $this->oPage->url;?>" />
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'url', 'sId' => 'pageUrl'))?>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="pageShortDescription" class="col-lg-1 control-label">Короткое описание</label>
                        <div class="col-lg-11">
                            <!--<input type="hidden" name="pageShortDescription" id="pageShortDescription" value="" />-->
                            <?php //echo $this->partial('partials/wysiwyg.phtml', array('id' => 'pageShortDescription', 'text' => $this->oPage->short_text,)) ?>
                            <textarea class="wysiwyg-redactor" name="pageShortDescription" id="pageShortDescription" style="width: auto; min-height: 600px;">
                                <?=$this->oPage->short_text?>
                            </textarea>
                        </div> 
                    </div>
                    
                    <div class="form-group">
                        <label for="pageText" class="col-lg-1 control-label">Подробное описание</label>
                        <div class="col-lg-11">
                            <!--<input type="hidden" name="pageText" id="pageText" value="" />-->
                            <?php //echo $this->partial('partials/wysiwyg.phtml', array('id' => 'pageText', 'text' => $this->oPage->text,)) ?>
                            <textarea class="wysiwyg-redactor" name="pageText" id="pageText" style="width: auto; min-height: 600px;">
                                <?=$this->oPage->text?>
                            </textarea>
                        </div> 
                    </div>

                    <div class="form-group">
                        <label for="pageIdStatus" class="col-lg-1 control-label">Статус</label>
                        <div class="col-lg-11">
                            <select class="form-control" name="pageIdStatus" id="pageIdStatus">
                                <?php foreach ($this->aStatuses as $oStatus) { ?>
                                <option value="<?php echo $oStatus->id_status;?>" <?php echo ($oStatus->id_status == $this->oPage->id_status)?'selected="selected"':'';?>><?php echo $oStatus->name;?></option>
                                <?php } ?>
                            </select>
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'id_status'))?>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="tab-seo">
                    <div class="form-group">
                        <label for="pageTitle" class="col-lg-1 control-label">Title</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control" name="pageTitle" id="pageTitle" placeholder="Title" value="<?php echo $this->oPage->title;?>" />
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'title'))?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="pageKeywords" class="col-lg-1 control-label">Keywords</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control" name="pageKeywords" id="pageKeywords" placeholder="Keywords" value="<?php echo $this->oPage->keywords;?>" />
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'keywords'))?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="pageDescription" class="col-lg-1 control-label">Description</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control" name="pageDescription" id="pageDescription" placeholder="Description" value="<?php echo $this->oPage->description;?>" />
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'description'))?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="pageRedirect" class="col-lg-1 control-label">Редирект</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control" name="pageRedirect" id="pageRedirect" placeholder="Полный URL" value="<?php echo $this->oPage->redirect;?>" />
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'redirect'))?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="pageRedirectCode" class="col-lg-1 control-label">Код редиректа</label>
                        <div class="col-lg-11">
                            <select class="form-control" name="pageRedirectCode" id="pageRedirectCode">
                                <option value="0">нет</option>
                                <?php foreach ($this->aRedirectCodes as $iCode => $sName) { ?>
                                <option value="<?php echo $iCode;?>">[<?php echo $iCode;?>] <?php echo $sName;?></option>
                                <?php } ?>
                            </select>
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'redirect_code'))?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-offset-1 col-lg-11">
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>
    </section>
</form>   
        
    