<?php echo $this->doctype() ?>
<html lang="en">
	<head>
		<title>Готовимся к зиме с lexusowners.ru</title>
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
                <?php echo $this->headMeta() ?>
                <?php echo $this->headLink() ?>
                <?php echo $this->headScript() ?>
		<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
                <!--[if lte IE 8]>
                    <script src="/domains/winter.lexusowners.ru/js/respond.min.js"></script>
                <![endif]-->
		<!--[if lt IE 9]>
			<script src="/domains/winter.lexusowners.ru/js/html5shiv.js"></script>
		<![endif]-->
                <!--[if lt IE 9]>
			<script type="text/javascript" src="/domains/winter.lexusowners.ru/js/skrollr.ie.min.js"></script>
		<![endif]-->
	</head>
	<body data-spy="scroll" data-target=".navbar" data-offset='61'>
		<div id="preloader">
			<div id="status">&nbsp;</div>
		</div>
	<!--start navigation-->
		<div class="navbar navbar-fixed-top" role="navigation">
			<div class="container" data-start="padding: 15px 0px;" data-200="padding: 0px 0px;">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="#intro" class="navbar-brand"><img class="img-responsive" src="http://placehold.it/166x40" alt=""></a>
				<div class="nav-collapse collapse navbar-responsive-collapse">
					<ul class="nav navbar-nav pull-right">
                                            <li><a href="#intro"><i class="icon icon-home"></i></a></li>
						<li><a href="#services">Сервис</a></li>
						<li><a href="#second">Пакеты</a></li>
						<li><a href="#third-header">Отзывы</a></li>
						<li><a href="#contact">Адрес</a></li>
					</ul>
				</div>
			</div>
		</div>
	<!--end navigation-->
	<!--start intro section-->
		<section id="intro">
			<div id="carousel_intro" class="carousel slide fadeing">
				<div class="carousel-inner">
					<div class="active item" id="slide_1" data-start="background-position: center 0px;" data-1440="background-position: center -250px;">
                                            <h1 data-start="opacity:1; top: 45%;" data-250="opacity: 0; top: 10%;"><i class="icon icon-asterisk"></i> Зима близко!</h1>
					</div>
					<div class="inactive item" id="slide_2" data-start="background-position: center 0px;" data-1440="background-position: center -250px;">
						<h1 data-start="opacity:1; top: 45%;" data-250="opacity: 0; top: 10%;"><i class="icon icon-thumbs-up"></i> Подготовьтесь ко встрече с ней!</h1>
					</div>
					<div class="inactive item" id="slide_3" data-start="background-position: center 0px;" data-1440="background-position: center -250px;">
						<h1 data-start="opacity:1; top: 45%;" data-250="opacity: 0; top: 10%;"><i class="icon icon-road"></i> Пакеты зимнего обслуживания для Lexus</h1>
					</div>
				</div>
			<button class="left carousel-control" href="#carousel_intro" data-slide="prev" data-start="opacity: 0.6; left: 0%;" data-250="opacity:0; left: 5%;"><i class="icon-chevron-left"></i></button>
			<button class="right carousel-control" href="#carousel_intro" data-slide="next" data-start="opacity: 0.6; right: 0%;" data-250="opacity:0; right: 5%;"><i class="icon-chevron-right"></i></button>
			</div>
			<div class="hidden-sm more">
				<a href="#services" class="btn btn-syndicate squared" data-start="opacity:1; margin-top: 0%;" data-250="opacity:0; margin-top: -10%;"><i class="icon-angle-down"></i> Узнайте, как подготовить ваш Lexus к зиме</a>
			</div>
		</section>
	<!--end intro section-->
	<!--start services section-->
		<section id="services">
			<div class="container">
				<div class="row">
					<div class="col-lg-12"> 
						<h1>Сервис</h1>
					</div>
					<div class="col-lg-3 col-sm-6 margin">
						<i class="icon-tablet red" data-bottom-center="opacity: 0;" data-bottom-bottom="opacity: 1;"></i>
						<h3>Fully Responsive</h3>
						<h5>Down to Phone Screen</h5>
						<p><small>A website that responds to the device that accesses it and delivers the appropriate output for it uses responsive design.</small></p>
					</div>
					<div class="col-lg-3 col-sm-6 margin">
						<i class="icon-cogs yellow" data-bottom-center="opacity: 0;" data--60-bottom-bottom="opacity: 1;"></i>
						<h3>Built With Bootstrap 3!</h3>
						<h5>HTML5 & CSS3 Valid Code</h5>
						<p><small>Sleek, intuitive, and powerful mobile-first front-end framework for faster and easier web development.</small></p>
					</div>
					<div class="col-lg-3 col-sm-6 margin">
						<i class="icon-eye-open green" data-bottom-center="opacity: 0;" data--120-bottom-bottom="opacity: 1;"></i>
						<h3>Retina Ready</h3>
						<h5>Ultra sharp graphics</h5>
						<p><small>Syndicate looks beautiful on retina displays. Makes it easy to serve high-resolution images to devices with retina displays.</small></p>
					</div>
					<div class="col-lg-3 col-sm-6 margin">
						<i class="icon-ambulance blue" data-bottom-center="opacity: 0;" data--180-bottom-bottom="opacity: 1;"></i>
						<h3>Free Support</h3>
						<h5>It's Free and Always Will Be</h5>
						<p><small>Don't worry - we've got you covered! Grab a cup of coffee and let us jump in. We also do small customization for free.</small></p>
					</div>
				</div>
			</div>
		</section>
	<!--end services section-->
		<div class="rainbow"></div>
	<!--start customers section-->
		<section id="customers">
			<div class="container">
				<div class="row">
					<div class="col-lg-2">
						<a href="#" target="blank"><img class="img-responsive" src="http://placehold.it/170x50" alt=""></a>
					</div>
					<div class="col-lg-2">
						<a href="#" target="blank"><img class="img-responsive" src="http://placehold.it/170x50" alt=""></a>
					</div>
					<div class="col-lg-2">
						<a href="#" target="blank"><img class="img-responsive" src="http://placehold.it/170x50" alt=""></a>
					</div>
					<div class="col-lg-2">
						<a href="#" target="blank"><img class="img-responsive" src="http://placehold.it/170x50" alt=""></a>
					</div>
					<div class="col-lg-2">
						<a href="#" target="blank"><img class="img-responsive" src="http://placehold.it/170x50" alt=""></a>
					</div>
					<div class="col-lg-2">
						<a href="#" target="blank"><img class="img-responsive" src="http://placehold.it/170x50" alt=""></a>
					</div>
				</div>
			</div>
		</section>
	<!--end customers section-->
		<div class="rainbow"></div>
	<!--start details section-->
		<section id="details">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<h1>Details</h1>
					</div>
					<div class="col-lg-4 col-sm-4 margin">
						<div class="row">
							<div class="col-lg-2 col-sm-2">
								<span class="icon-stack">
									<i class="icon-circle icon-stack-base red"></i>
									<i class="icon-file-text icon-light" data-bottom-center="font-size: 5em; opacity: 0;" data--200-bottom-bottom="font-size: 1.4em; opacity: 1;"></i>
								</span>
							</div>
							<div class="col-lg-10 col-sm-10">
								<h3>Well Documented</h3>
								<p><small>We have explained how to edit every element for your needs. All packed in one nice document that comes with download.</small></p>
							</div>
							<div class="col-lg-2 col-sm-2">
								<span class="icon-stack">
									<i class="icon-circle icon-stack-base red"></i>
									<i class="icon-code icon-light" data-bottom-center="font-size: 5em; opacity: 0;" data--200-bottom-bottom="font-size: 1.4em; opacity: 1;"></i>
								</span>
							</div>
							<div class="col-lg-10 col-sm-10">
								<h3>Commented</h3>
								<p><small>To help you when customizing Syndicate, HTML and CSS files are commented.</small></p>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-sm-4 margin">
						<div class="row">
							<div class="col-lg-2 col-sm-2">
								<span class="icon-stack">
									<i class="icon-circle icon-stack-base yellow"></i>
									<i class="icon-comments icon-light" data-bottom-center="font-size: 5em; opacity: 0;" data--200-bottom-bottom="font-size: 1.4em; opacity: 1;"></i>
								</span>
							</div>
							<div class="col-lg-10 col-sm-10">
								<h3>Support via forum</h3>
								<p><small>We have forum for our buyers where you can report issues, find answers and get latest updates before we publish them on ThemeForest.</small></p>
							</div>
							<div class="col-lg-2 col-sm-2">
								<span class="icon-stack">
									<i class="icon-circle icon-stack-base yellow"></i>
									<i class="icon-envelope icon-light" data-bottom-center="font-size: 5em; opacity: 0;" data--200-bottom-bottom="font-size: 1.4em; opacity: 1;"></i>
								</span>
							</div>
							<div class="col-lg-10 col-sm-10">
								<h3>Support via email</h3>
								<p><small>If you have some pre-sale questions you can always contact us via form on our ThemeForest profile.</small></p>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-sm-4 margin">
						<div class="row">
							<div class="col-lg-2 col-sm-2">
								<span class="icon-stack">
									<i class="icon-circle icon-stack-base green"></i>
									<i class="icon-html5 icon-light" data-bottom-center="font-size: 5em; opacity: 0;" data--200-bottom-bottom="font-size: 1.4em; opacity: 1;"></i>
								</span>
							</div>
							<div class="col-lg-10 col-sm-10">
								<h3>HTML5 & CSS3</h3>
								<p><small>Valid code, latest technologies, always up-to-date. Compatible with latest desktop and mobile browsers down to IE8.</small></p>
							</div>
							<div class="col-lg-2 col-sm-2">
								<span class="icon-stack">
									<i class="icon-circle icon-stack-base green"></i>
									<i class="icon-bug icon-light" data-bottom-center="font-size: 5em; opacity: 0;" data--200-bottom-bottom="font-size: 1.4em; opacity: 1;"></i>
								</span>
							</div>
							<div class="col-lg-10 col-sm-10">
								<h3>No Bugs</h3>
								<p><small>Syndicate is tested on different devices, browsers and operating systems. If you find one, the beer is on us.</small></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	<!--end details section-->
	<!--start first header section-->
		<section id="first-header" class="header slider-header">
			<h1>One for all</h1>
			<div id="carousel_header_1" class="carousel slide fadeing">
				<div class="carousel-inner">
					<div class="active item">
						<img class="img-responsive" src="http://placehold.it/570x345" alt="">
					</div>
					<div class="inactive item">
						<img class="img-responsive" src="http://placehold.it/570x345" alt="">
					</div>
					<div class="inactive item">
						<img class="img-responsive" src="http://placehold.it/570x345" alt="">
					</div>
				</div>
				<button class="left carousel-control" href="#carousel_header_1" data-slide="prev"><i class="icon-chevron-left"></i></button>
				<button class="right carousel-control" href="#carousel_header_1" data-slide="next"><i class="icon-chevron-right"></i></button>
			</div>
		</section>
	<!--end first header section-->
	<!--start first section-->
		<section id="first" class="content">
			<div class="container">
				<div class="row">
	<!--start features #1 -->
					<div class="col-lg-6">
						<h1>It's Awesome</h1>
						<p class="lead">With Bootstrap 3, Syndicate is mobile friendly from the start. 
						Instead of adding on optional mobile styles, they're baked right into the core. In fact, Syndicate is mobile first.<br><br>
						<small>The rset can be a toatl mses and you can sitll raed it wouthit porbelm. 
						Tihs is bcuseae the huamn mnid deos not raed ervey lteter by istlef, but the wrod as a wlohe. 
						Awesomeness, true story!</small></p>
					</div>
					<div class="col-lg-6 icons">
						<div class="row">
							<div class="col-lg-2 col-sm-2">
								<i class="icon-group" data-bottom-center="font-size: 0px;" data-center-top="font-size: 52px;"></i>
							</div>
							<div class="col-lg-10 col-sm-10">
								<a href="#" class="btn btn-more btn-mini">More</a>
								<h3>Made for Everyone</h3>
								<h5>Packed with Features</h5>
								<p><small>Global CSS settings, fundamental HTML elements styled and enhanced with extensible classes and an advanced grid system.</small></p>
							</div>
							<div class="col-lg-2 col-sm-2">
								<i class="icon-flag" data-bottom-center="font-size: 0px;" data-center-top="font-size: 52px;"></i>
							</div>
							<div class="col-lg-10 col-sm-10">
								<a href="#" class="btn btn-more btn-mini">More</a>
								<h3>Tons of Components</h3>
								<h5>Add any, fast and easy</h5>
								<p><small>Dozens of reusable components built to provide dropdowns, navigation, alerts, popovers and much more.</small></p>
							</div>
						</div>
					</div>
				</div>
				<div class="content-divider"></div>
	<!--start features #5 / tables -->
				<div class="row margin">
					<div class="col-lg-8 col-offset-2">
						<h1 class="text-center">Зимние пакеты</h1>
						<p class="text-center"><small>Никаких навязанных услуг и скрытых платежей. Мы против мелкого шрифта!</small></p>
					</div>
					<div class="col-lg-4 col-sm-4">
						<div class="pricing-table red">
							<h3><span>ЛАЙТ</span></h3><br>
							<h2>1200</h2>
							<i class="icon-gear"></i>
							<p>Идеально для машин с маленьким пробегом</p>
							<h3><span>Услуги</span></h3><br>
							<p>&mdash; проверка состояния подвески</p>
                                                        <p>&mdash; проверка состояния аккумулятора</p>
                                                        <p>&mdash; проверка плотности антифриза</p>
                                                        <p>&mdash; проверка и регулировка световых приборов</p>
							<p><a class="btn btn-pallmall" href="#">Записаться</a></p>
						</div>
					</div>
					<div class="col-lg-4 col-sm-4">
						<div class="pricing-table yellow">
							<h3><span>СТАНДАРТ</span></h3><br>
							<h2>2500</h2>
							<i class="icon-gears"></i>
							<p>Для машин с пробегом свыше 100 тысяч километров или старше 5 лет</p>
							<h3><span>Услуги</span></h3><br>
							<p>&mdash; пакет лайт</p>
                                                        <p>&mdash; проверка электронных систем активной безопасности (ABS, EBD, VSC, TRC)</p>
                                                        <p>&mdash; проверка электронных систем пассивной безопасности (SRS)</p>
                                                        <p>&mdash; проверка двигателя и АКПП</p>
							<p><a class="btn btn-sun" href="#">Записаться</a></p>
						</div>
					</div>
					<div class="col-lg-4 col-sm-4">
						<div class="pricing-table green">
							<h3><span>ПРОФЕССИОНАЛ</span></h3><br>
							<h2>6500</h2>
							<i class="icon-heart"></i>
							<p>Полный пакет обслуживания для любимой машины</p>
							<h3><span>Услуги</span></h3><br>
							<p>&mdash; пакет стандарт</p>
                                                        <p>&mdash; замена салонного и воздушного фильтров (фильтры входят в стоимость пакета)</p>
                                                        <p>&mdash; замена щеток стеклоочистителя (комплект щеток входит в стоимость пакета)</p>
							<p><a class="btn btn-eco" href="#">Записаться</a></p>
						</div>
					</div>
				</div>
				<div class="content-divider"></div>
				<div class="row">
					<div class="col-lg-8 col-offset-2 text-center">
						<h1 class="text-center">Остались вопросы?</h1>
						<p class="text-center">Оставьте заявку. Наш менеджер свяжется с вами и пояснит криком блять<br><br>
						<a class="btn btn-syndicate btn-large squared" href="#">Оставить заявку</a></p>
					</div>
				</div>
				<div class="content-divider"></div>
			</div>
		</section>
	<!--end first section-->
	<!--start third header section-->
		<section id="third-header" class="header header-extended">
			<div id="carousel_header_3" class="carousel slide fadeing">
				<div class="carousel-inner">
					<div class="active item">
						<h1>Всё еще не уверены?</h1>
						<p class="lead">Просто ознакомьтесь с отзывами наших клиентов и решение придет само собой</p>
						<button class="btn btn-fancy squared" href="#">Читать отзывы</button>
					</div>
					<div class="inactive item">
						<h1>И всё равно не уверены?</h1>
						<p class="lead">Мы гарантируем качество нашей работы или вернём деньги!</p>
						<button class="btn btn-fancy squared" href="#">Оставить заявку</button>
					</div>
				</div>
				<button class="left carousel-control" href="#carousel_header_3" data-slide="prev"><i class="icon-chevron-left"></i></button>
				<button class="right carousel-control" href="#carousel_header_3" data-slide="next"><i class="icon-chevron-right"></i></button>
			</div>
		</section>
	<!--end third header section-->
	<!--start third section-->
		<section id="third" class="content team">
			<div class="container">
				<div class="row">
					<div class="col-lg-8 col-offset-2">
						<h1 class="text-center">Клиенты говорят</h1>
						<p class="text-center">Мы ценим своих клиентов и с уважением относимся к их мнению</p>
					</div>
					<div class="col-lg-6 col-sm-6">
						<blockquote>
							<p>Недалеко от дома и соотношение цены и качества более чем устраивает.
							<small>Сергей, <cite title="">Lexus GS300</cite></small></p>
						</blockquote>
					</div>
					<div class="col-lg-6 col-sm-6">
						<blockquote>
							<p>Вполне устраивает как качество работ, так и их стоимость. Из мастеров порекомендую Юрия.
							<small>Виктор, <cite title="">Lexus GS350</cite></small></p>
						</blockquote>
					</div>
					<div class="col-lg-6 col-sm-6">
						<blockquote>
                                                    <p>Не нужно записываться за месяц, как к официалам, цены вполне народные, муж перестал ворчать по поводу денег на обслуживание <i class="icon icon-smile"></i>
							<small>Ирина, <cite title="">Lexus RX450h</cite></small></p>
						</blockquote>
					</div>
					<div class="col-lg-6 col-sm-6">
						<blockquote>
							<p>Можно оставить машину с утра и вечером забрать уже готовую. Ребята, хоть и молодые, но толковые.
							<small>Константин Сергеевич, <cite title="">Lexus LS460</cite></small></p>
						</blockquote>
					</div>
					<div class="col-lg-6 col-sm-6">
						<blockquote>
							<p>Отремонтировали и покрасили машину после ДТП. Не сильно дешевле рынка вышло, но к качеству нареканий нет. Буду советовать друзьям.
							<small>Юрий, <cite title="">Lexus IS250</cite></small></p>
						</blockquote>
					</div>
                                        <div class="col-lg-6 col-sm-6">
						<blockquote>
							<p>Перепробовал много техцентров, но напрягало непостоянство качества работы и небрежное отношение 
                                                        персонала к автомобилю клиента, в итоге уже 3 года с вами.
							<small>Максим, <cite title="">Lexus SC430</cite></small></p>
						</blockquote>
					</div>
				</div>
				<div class="divider"></div>
			</div>
		</section>
	<!--end third section-->
	<!--start contact section-->
		<section id="contact" class="content no-header">
			<div class="container">
				<div class="content-divider"></div>
				<div class="row">
					<div class="col-lg-8 col-offset-2">
						<h1 class="text-center">Как нас найти</h1>
						<p class="text-center">Проехать к нам довольно просто</p>
					</div>
					<div class="col-lg-12">
						<div class="row">
							<form action="js/sendmail.php" class="form-inline" role="form" method="post" id="contactForm">
								<div class="form-group col-lg-3 col-sm-6">
									<label>Name:</label>
									<input type="text" name="name" value="" id="name" class="form-control">
								</div>
								<div class="form-group col-lg-3 col-sm-6">
									<label>Email:</label>
									<input type="text" name="email" value="" id="email" class="form-control">
								</div>
								<span class="honeypot">
									<label>Honeypot:</label>
									<input type="text" name="last" value="" id="last">
								</span>
								<div class="form-group col-lg-3 col-sm-6">
									<label>Message:</label>
									<input type="text" name="message" value="" id="message" class="form-control">
								</div>
								<div class="form-group col-lg-3 col-sm-6">
									<label>Done?</label>
									<div class="message">
										<div class="alert"></div>
									</div>
									<button type="submit" value="Send" id="submit" class="btn btn-syndicate btn-block">Send</button>
								</div>
							</form>
						</div>
					</div>
				</div>
				<div class="divider"></div>
				<div class="row">
					<div class="col-lg-3 col-sm-3">
						<h3>Hello!</h3><br>
						<blockquote>We would be more than happy to chat with you.</blockquote>
					</div>
					<div class="col-lg-3 col-sm-3">
						<h3>Visit us:</h3><br>
						<blockquote>795 Folsom St., Suite 600<br> San Francisco, CA 94107</blockquote>
					</div>
					<div class="col-lg-3 col-sm-3">
						<h3>Mail us:</h3><br>
						<blockquote>general: office@syndicate.com<br> support: support@syndicate.com</blockquote>
					</div>
					<div class="col-lg-3 col-sm-3">
						<h3>Call us:</h3><br>
						<blockquote>P: (123) 456-7890<br> F: (123) 456-7890</blockquote>
					</div>
				</div>
			</div>
		</section>
	<!--end contact section-->
	<!--start footer section-->
		<section id="footer">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 col-sm-6 margin copy">
						<p>2013 &copy; Lexusowners.ru - Специальный пакет зимних услуг</p>
					</div>
					<div class="col-lg-4 col-sm-6 col-offset-2 margin social">
						
					</div>
				</div>
			</div>
		</section>
	<!--end footer section-->
        <?php echo $this->layout()->content ?>
	<!--start back to top button-->
		<a href="#intro" class="hidden-sm go-top" data-0="opacity: 0;" data-1000="opacity: 1;">Наверх</a>
	<!--end back to top button-->
	<!--menu close on select-->
		<script>
			if ($('.navbar-toggle:visible').length) {
				$('.navbar a').click(function () { $(".nav-collapse").collapse("hide") });
			}
		</script>
	</body>
</html>