<div class="m-b-md">
    <h3 class="m-b-none">Статические страницы</h3>
</div>

<section class="panel panel-default">
    <header class="panel-heading">
      Статические страницы
    </header>
    <div class="row text-sm wrapper">
        <div class="col-sm-5 m-b-xs">
            <a href="<?php echo $this->url(array('iPageId' => 0,), 'pages-edit')?>" class="btn btn-sm btn-success" title="Создать"><i class="fa fa-plus-circle"></i></a>
        </div>
        <div class="col-sm-4 m-b-xs"></div>
        <div class="col-sm-3">
            <div class="input-group">
                <input type="text" class="input-sm form-control" placeholder="Поиск">
                <span class="input-group-btn">
                    <button class="btn btn-sm btn-default" type="button">Искать</button>
                </span>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped b-t b-light text-sm">
            <thead>
                <tr>
                    <th width="20"><input type="checkbox"></th>
                    <th>ID</th>
                    <th>Название</th>
                    <th>Проект</th>
                    <th>URL</th>
                    <th>Статус</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->oPages->count() > 0) { ?>
                <?php foreach ($this->oPages->getCurrentItems() as $oPage) { ?>
                <tr>
                    <td><input type="checkbox" name="page_selected[]" value="2"></td>
                    <td><?php echo $oPage->id_page;?></td>
                    <td><?php echo $oPage->name?></td>
                    <td><?=Mg_Common_Helper_Domain::getDomainNameByKey($oPage->domain_key)?></td>
                    <td><?php echo $oPage->url;?></td>
                    <td><?php echo $this->aStatuses[$oPage->id_status]->name?></td>
                    <td>
                        <a href="<?php echo $this->url(array('iPageId' => $oPage->id_page,), 'pages-edit');?>" title="Редактировать"><i class="fa fa-edit"></i></a> 
                        <a href="#" title="Удалить"> <i class="fa fa-trash-o"></i> </a>
                    </td>
                </tr>
                <?php } ?>
                <?php } else { ?>
                <tr>
                    <td colspan="6">
                        <div class="alert alert-info">
                            <i class="fa fa-info-circle"></i> <b>В данной категории нет страниц</b>
                        </div>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <footer class="panel-footer">
        <div class="row">
            <div class="col-sm-4 hidden-xs"></div>
            <div class="col-sm-4 text-center"></div>
            <div class="col-sm-4 text-right text-center-xs">
                <?php echo $this->paginationControl($this->oPages, 'Sliding', 'partials/pagination.phtml');?>
            </div>
        </div>
    </footer>
</section>