<div class="m-b-md">
    <h3 class="m-b-none">
        <?php if ($this->oCategory->id_category > 0) { ?>
        Категория &laquo;<?php echo $this->oCategory->name?>&raquo;
        <?php } else { ?>
        Магазин &laquo;<?php echo $this->oShop->name?>&raquo;
        <?php } ?>
    </h3>
</div>
<section class="panel panel-default">
    <header class="panel-heading">
      Категории
    </header>
    <div class="row text-sm wrapper">
        <div class="col-sm-5 m-b-xs">
            <a href="<?php echo $this->url(array('iShopId' => $this->oShop->id_shop, 'iCategoryId' => 0, 'iParentId' => $this->oCategory->id_category,), 'shop-categories-edit')?>" class="btn btn-sm btn-success" title="Создать"><i class="fa fa-plus-circle"></i></a>
        </div>
        <div class="col-sm-4 m-b-xs"></div>
        <div class="col-sm-3">
            <div class="input-group">
                <input type="text" class="input-sm form-control" placeholder="Поиск">
                <span class="input-group-btn">
                    <button class="btn btn-sm btn-default" type="button">Искать</button>
                </span>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped b-t b-light text-sm">
            <thead>
                <tr>
                    <th width="20"><input type="checkbox"></th>
                    <th>ID</th>
                    <th class="th-sortable" data-toggle="class">Название
                        <span class="th-sort">
                            <i class="fa fa-sort-down text"></i>
                            <i class="fa fa-sort-up text-active"></i>
                            <i class="fa fa-sort"></i>
                        </span>
                    </th>
                    <th>Товары</th>
                    <th>URL</th>
                    <th>Статус</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->oCategory->id_category > 0) { ?>
                <tr>
                    <td><i class="fa fa-reply"></i></td>
                    <td colspan="6"><a href="<?php echo $this->url(array('iShopId' => $this->oCategory->id_shop, 'iCategoryId' => $this->oCategory->id_parent, 'iPage' => 1,), 'shop-categories-list') ?>"><b>..</b></a></td>
                </tr>
                <?php } ?>
                <?php if ($this->oCategories->count() > 0) { ?>
                <?php foreach ($this->oCategories->getCurrentItems() as $oCategory) { ?>
                <tr>
                    <td>
                    <?php if ($oCategory->cross_flag) { ?>
                        <i class="fa fa-random" title="Кросс-категория"></i>
                    <?php } else { ?>
                        <input type="checkbox" name="shop_selected[]" value="2">
                    <?php } ?>
                    </td>
                    <td><?php echo $oCategory->id_category;?></td>
                    <td><a href="<?php echo $this->url(array('iShopId' => $oCategory->id_shop, 'iCategoryId' => $oCategory->id_category, 'iPage' => 1,), 'shop-categories-list') ?>"><b><?php echo $oCategory->name?></b></a></td>
                    <td><a href="<?php echo $this->url(array('iShopId' => $oCategory->id_shop, 'iCategoryId' => $oCategory->id_category,), 'shop-categories-items-list') ?>"><i class="fa fa-bars"></i> (<?php echo Mg_Shop_Helper_Item::getCountByCategory($oCategory->id_category) ?>)</a></td>
                    <td><?php echo $oCategory->url;?></td>
                    <td><?php echo $this->aStatuses[$oCategory->id_status]->name?></td>
                    <td>
                        <a href="<?php echo $this->url(array('iShopId' => $oCategory->id_shop,'iCategoryId' => $oCategory->id_category,), 'shop-categories-edit');?>" title="Редактировать"><i class="fa fa-edit"></i></a> 
                        <a href="#" title="Удалить"><i class="fa fa-trash-o"></i> </a>
                    </td>
                </tr>
                <?php } ?>
                <?php } else { ?>
                <tr>
                    <td colspan="7">
                        <div class="alert alert-info">
                            <i class="fa fa-info-circle"></i> <b>Нет ни одной категории</b>
                        </div>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <footer class="panel-footer">
        <div class="row">
            <div class="col-sm-4 hidden-xs"></div>
            <div class="col-sm-4 text-center"></div>
            <div class="col-sm-4 text-right text-center-xs">
                <?php echo $this->paginationControl($this->oCategories, 'Sliding', 'partials/pagination.phtml');?>
            </div>
        </div>
    </footer>
</section>