<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
          <span class="sr-only">Меню</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
    <a class="navbar-brand" href="/">Multitronics.ru</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/about">О компании</a></li>
        <li><a href="#">Продукция</a></li>
        <li><a href="#">Сервис</a></li>
        <li><a href="/sertiphikaty">Сертификаты</a></li>
        <li><a href="#">Цены</a></li>
        <li><a href="#">Где купить</a></li>
        <li><a href="#">Вакансии</a></li>
        <li><a href="<?=$this->url(array(), 'codes-default')?>">Коды ошибок</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Профиль</a></li>
      </ul>
    </div>
  </div>
</nav>