<section>
    <div class="page-info-3">
        <div class="container">
            <h3><?php echo $this->oElement->name ?></h3> 
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">          
                <div class="blog-container">        
                    <div class="blog-text">
                        <p><?php echo $this->oElement->text ?></p>
                    </div>
                </div><!-- blog container end -->
                <hr class="medium-line">
            </div>
        </div>
        <div class="row spacer60"></div>
    </div>
</section>