<div class="m-b-md">
    <h3 class="m-b-none">DEV PANEL</h3> 
</div>
<form action="<?=$this->url()?>" method="POST" enctype="multipart/form-data" class="form-horizontal">
    <section class="panel panel-default">
        <div class="panel-body">
            <div class="form-group">
                <label for="iObjId" class="col-lg-1 control-label">iObjId</label>
                <div class="col-lg-11">
                    <input type="text" class="form-control" name="iObjId" id="iObjId" placeholder="iObjId" value="1" />
                </div>
            </div>
            <div class="form-group">
                <label for="iObjType" class="col-lg-1 control-label">iObjType</label>
                <div class="col-lg-11">
                    <input type="text" class="form-control" name="iObjType" id="iObjType" placeholder="iObjType" value="1" />
                </div>
            </div>
            <div class="form-group">
                <label for="aFile" class="col-lg-1 control-label">aFile</label>
                <div class="col-lg-11">
                    <input type="file" class="form-control" name="aFile[]" id="aFile" />
                    <input type="file" class="form-control" name="aFile[]" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-12">
                    <button type="submit" class="btn btn-success">Post</button>
                </div>
            </div>
        </div>
    </section>
</form>

<section class="panel panel-default">
    <div class="panel-body">
        <?php foreach ($this->aFiles as $iKey=>$aFile) { ?>
        <a href="/pub_img<?=$this->aOrigFiles[$iKey]['url']?>" target="_blank"><img src="/pub_img<?=$aFile['url']?>" /></a><br/><br/>
        <?php } ?>
    </div>
</section>