<div class="m-b-md">
    <h3 class="m-b-none">YA maps test tool</h3> 
</div>

<section class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" action="<?=$this->url()?>" method="POST">
            <div class="form-group">
                <label class="col-sm-2 control-label">Запрос</label>
                <div class="col-sm-10">
                    <input type="text" name="geocode" class="form-control rounded" value="<?=$this->aParams['geocode']?>">                        
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </div>
            </div>
        </form>
        Результат:<br/>
        <pre><?=print_r($this->sResult, true)?></pre>
    </div>
</section>

