<ul class="nav navbar-nav navbar-right hidden-xs nav-user">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="thumb-sm avatar pull-left">
                <img src="/domains/admin/images/avatar.jpg">
            </span>
            <?=($this->oUser->nickname)?$this->oUser->nickname:$this->oUser->email?> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu animated fadeInRight">
            <span class="arrow top"></span>
            <li>
                <a href="#">Settings</a>
            </li>
            <li>
                <a href="profile.html">Profile</a>
            </li>
            <li>
                <a href="#">
                    <span class="badge bg-danger pull-right">3</span>
                    Notifications
                </a>
            </li>
            <li>
                <a href="docs.html">Help</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="<?php echo $this->url(array(), 'unauth')?>">Выход</a>
            </li>
        </ul>
    </li>
</ul>