<?php if (!empty($this->pages)) { ?>
<ol class="breadcrumb">
<?php foreach ($this->pages as $iIndex => $oPage) { ?>
    <?php if ($oPage->isActive()) { ?>
    <li class="active"><?php echo $oPage->getLabel(); ?></li>
    <?php } else { ?>
    <li><a href="<?php echo $oPage->getHref(); ?>"><?php echo ($iIndex == 0)?'<i class="fa fa-rocket"></i> ':''?><?php echo $oPage->getLabel(); ?></a></li>
    <?php } ?>
<?php } ?>
</ol>
<?php } ?>