<div class="wrapper-wysiwyg" id="wrapper-wysiwyg-<?php echo $this->id?>" style="background-color: #ffffff;">
<div class="btn-toolbar m-b-sm btn-editor" data-role="editor-toolbar" data-target="#wysiwyg-<?php echo $this->id?>" id="wysiwyg-toolbar-<?php echo $this->id?>">
    <div class="btn-group">
        <a class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" title="Размер текста"><i class="fa fa-text-height"></i>&nbsp;<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a data-edit="fontSize 5"><font size="5">Большой</font></a></li>
            <li><a data-edit="fontSize 3"><font size="3">Средний</font></a></li>
            <li><a data-edit="fontSize 1"><font size="1">Маленький</font></a></li>
        </ul>
    </div>
    <div class="btn-group">
        <a class="btn btn-default btn-sm" data-edit="bold" title="Жирный (Ctrl/Cmd+B)"><i class="fa fa-bold"></i></a>
        <a class="btn btn-default btn-sm" data-edit="italic" title="Курсив (Ctrl/Cmd+I)"><i class="fa fa-italic"></i></a>
        <a class="btn btn-default btn-sm" data-edit="strikethrough" title="Зачеркнуто"><i class="fa fa-strikethrough"></i></a>
        <a class="btn btn-default btn-sm" data-edit="underline" title="Подчеркнуто (Ctrl/Cmd+U)"><i class="fa fa-underline"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default btn-sm" data-edit="insertunorderedlist" title="Список"><i class="fa fa-list-ul"></i></a>
        <a class="btn btn-default btn-sm" data-edit="insertorderedlist" title="Нумерованный список"><i class="fa fa-list-ol"></i></a>
        <a class="btn btn-default btn-sm" data-edit="outdent" title="Уменьшить отступ (Shift+Tab)"><i class="fa fa-dedent"></i></a>
        <a class="btn btn-default btn-sm" data-edit="indent" title="Увеличить отступ (Tab)"><i class="fa fa-indent"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default btn-sm" data-edit="justifyleft" title="Выровнять слева (Ctrl/Cmd+L)"><i class="fa fa-align-left"></i></a>
        <a class="btn btn-default btn-sm" data-edit="justifycenter" title="Выровнять по центру (Ctrl/Cmd+E)"><i class="fa fa-align-center"></i></a>
        <a class="btn btn-default btn-sm" data-edit="justifyright" title="Выровнять справа (Ctrl/Cmd+R)"><i class="fa fa-align-right"></i></a>
        <a class="btn btn-default btn-sm" data-edit="justifyfull" title="Выровнять по ширине (Ctrl/Cmd+J)"><i class="fa fa-align-justify"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" title="Ссылка"><i class="fa fa-link"></i></a>
        <div class="dropdown-menu">
            <div class="input-group m-l-xs m-r-xs">
                <input class="form-control input-sm" placeholder="URL" type="text" data-edit="createLink"/>
                <div class="input-group-btn">
                    <button class="btn btn-default btn-sm" type="button"><i class="fa fa-plus-circle"></i></button>
                </div>
            </div>
        </div>
        <a class="btn btn-default btn-sm" data-edit="unlink" title="Удалить ссылку"><i class="fa fa-cut"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default btn-sm" title="Добавить картинку" id="pictureBtn-<?php echo $this->id?>"><i class="fa fa-picture-o"></i></a>
        <input type="file" data-role="magic-overlay" data-target="pictureBtn-<?php echo $this->id?>" data-edit="insertImage" />
    </div>
    <div class="btn-group">
        <a class="btn btn-default btn-sm" data-edit="undo" title="Отменить (Ctrl/Cmd+Z)"><i class="fa fa-undo"></i></a>
        <a class="btn btn-default btn-sm" data-edit="redo" title="Повторить (Ctrl/Cmd+Y)"><i class="fa fa-repeat"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default btn-sm" data-edit="fullscreen" title="На весь экран"><i class="fa fa-arrows"></i></a>
    </div>
</div>
<div id="wysiwyg-<?php echo $this->id?>" data-toolbar="wysiwyg-toolbar-<?php echo $this->id?>" class="form-control wysiwyg-editor" style="overflow:scroll;height:250px;max-height:400px">
<?php echo $this->text?>
</div>
</div>