<div class="m-b-md">
    <h3 class="m-b-none"><?php echo (strlen($this->oUser->id_user) > 0)? $this->oUser->nickname : 'Новый пользователь' ?></h3> 
</div>
<form role="form" id="user-edit-form" class="form-horizontal" method="POST" action="<?php echo $this->url();?>">
    <section class="panel panel-default">
        <header class="panel-heading bg-light">
            <ul class="nav nav-tabs nav-justified">
                <li class="active"><a href="#tab-page" data-toggle="tab">Пользователь</a></li>
            </ul>
        </header>
        <div class="panel-body">
            <div class="tab-content">
                <div class="tab-pane active" id="tab-page">
                    
                    <div class="form-group <?php echo (!empty($this->aErrors['nickname'])) ? 'has-error' : '' ?>">
                        <label for="userNickname" class="col-lg-1 control-label">Имя</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control validateable" name="userNickname" id="userNickname" data-cname="user" data-field="nickname" data-params="" placeholder="Иван Иванов" value="<?php echo $this->oUser->nickname;?>" />
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'nickname'))?>
                        </div>
                    </div>
                    
                    <div class="form-group <?php echo (!empty($this->aErrors['email'])) ? 'has-error' : '' ?>">
                        <label for="userEmail" class="col-lg-1 control-label">Email</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control validateable" name="userEmail" id="userEmail" data-cname="user" data-field="email" data-params="" placeholder="ivan@ivanov.com" value="<?php echo $this->oUser->email;?>" />
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'email'))?>
                        </div>
                    </div>
                    
                    <div class="form-group <?php echo (!empty($this->aErrors['phone'])) ? 'has-error' : '' ?>">
                        <label for="userPhone" class="col-lg-1 control-label">Телефон</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control validateable" name="userPhone" id="userPhone" data-cname="user" data-field="phone" data-params="" placeholder="9261112233" value="<?php echo $this->oUser->phone;?>" />
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'phone'))?>
                        </div>
                    </div>
                    
                    <div class="form-group <?php echo (!empty($this->aErrors['password'])) ? 'has-error' : '' ?>">
                        <label for="userPassword" class="col-lg-1 control-label">Пароль</label>
                        <div class="col-lg-11">
                            <input type="text" class="form-control validateable" name="userPassword" id="userPassword" data-cname="user" data-field="password" data-params="" placeholder="" value="" />
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'password'))?>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="userRole" class="col-lg-1 control-label">Роль</label>
                        <div class="col-lg-11">
                            <select class="form-control" name="userRole" id="userRole">
                                <?php foreach ($this->aRoles as $sRoleId => $sRoleName) { ?>
                                <option value="<?php echo $sRoleId;?>" <?php echo ($sRoleId == $this->oUser->role)?'selected="selected"':'';?>><?php echo $sRoleName;?></option>
                                <?php } ?>
                            </select>
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'role'))?>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="userIdStatus" class="col-lg-1 control-label">Статус</label>
                        <div class="col-lg-11">
                            <select class="form-control" name="userIdStatus" id="userIdStatus">
                                <?php foreach ($this->aStatuses as $oStatus) { ?>
                                <option value="<?php echo $oStatus->id_status;?>" <?php echo ($oStatus->id_status == $this->oUser->id_status)?'selected="selected"':'';?>><?php echo $oStatus->name;?></option>
                                <?php } ?>
                            </select>
                            <?=$this->partial('partials/form-errors.phtml', array('aErrors' => $this->aErrors, 'sField' => 'id_status'))?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-offset-1 col-lg-11">
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>
    </section>
</form>   
        
    